name       : uchardet
version    : 0.0.6
release    : 1
source     :
    - https://www.freedesktop.org/software/uchardet/releases/uchardet-0.0.6.tar.xz : 8351328cdfbcb2432e63938721dd781eb8c11ebc56e3a89d0f84576b96002c61
license    : MPL-1.1
component  : programming.library
summary    : An encoding detector library, which takes a sequence of bytes in an unknown character encoding without any additional information, and attempts to determine the encoding of the text
description: |
    An encoding detector library, which takes a sequence of bytes in an unknown character encoding without any additional information, and attempts to determine the encoding of the text
setup      : |
    %cmake -DBUILD_STATIC=0 .
build      : |
    %make
install    : |
    %make_install
