name       : uchardet
version    : 0.0.7
release    : 2
source     :
    - https://www.freedesktop.org/software/uchardet/releases/uchardet-0.0.7.tar.xz : 3fc79408ae1d84b406922fa9319ce005631c95ca0f34b205fad867e8b30e45b1
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MPL-1.1
component  : programming.library
summary    : An encoding detector library, which takes a sequence of bytes in an unknown character encoding without any additional information, and attempts to determine the encoding of the text
description: |
    An encoding detector library, which takes a sequence of bytes in an unknown character encoding without any additional information, and attempts to determine the encoding of the text
setup      : |
    %cmake_ninja -DBUILD_STATIC=0
build      : |
    %ninja_build
install    : |
    %ninja_install
